#!/bin/sh
#
# @name Skywinger
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

# Do NOT change the motor roration but only change the FC board rotation.
# Otherwise the aircraft becomes unstable!
param set-default SENS_BOARD_Y_OFF 30

param set-default CA_ROTOR0_PX 0.24
param set-default CA_ROTOR0_PY 0.48
param set-default CA_ROTOR0_PZ 0.15
param set-default CA_ROTOR0_KM  0.05

param set-default CA_ROTOR1_PX -0.27
param set-default CA_ROTOR1_PY -0.48
param set-default CA_ROTOR1_PZ -0.15
param set-default CA_ROTOR1_KM  0.05

param set-default CA_ROTOR2_PX 0.24
param set-default CA_ROTOR2_PY -0.48
param set-default CA_ROTOR2_PZ 0.15
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.27
param set-default CA_ROTOR3_PY 0.48
param set-default CA_ROTOR3_PZ -0.15
param set-default CA_ROTOR3_KM -0.05

param set-default MPC_THR_HOVER 0.60

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
